 baseURL = "https://jankremer.eu/"
title = "Jan Kremer"
paginate = 5
theme = "PaperMod"
languageCode = "de-de"
defaultContentLanguage = "de"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[languages.de]
languageName = "DE"
weight = 1

[languages.en]
languageName = "EN"
weight = 2

  [languages.en.homeInfoParams]
  Title = "Welcome to Jan Kremer's Blog 🧪"
  Content = "This is a small project I set up to learn about programming and to write small blog posts."

[[languages.en.menu.main]]
identifier = "posts"
url = "/posts"
name = "Posts"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About me"
url = "/about"
weight = 20

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 30

[[menu.main]]
identifier = "posts"
url = "/posts"
name = "Posts"
weight = 10

[[menu.main]]
identifier = "about"
name = "Über mich"
url = "/about"
weight = 20

[[menu.main]]
identifier = "search"
name = "Suche"
url = "/search"
weight = 30

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Jan Kremer"
description = "Blog von Jan Kremer mit Lebenslauf"
author = "Jan Kremer"
keywords = [ "Blog", "Portfolio", "Lebenslauf", "CV" ]
DateFormat = "2006-01-02"
defaultTheme = "auto"
disableThemeToggle = false
displayFullLangName = true
ShowReadingTime = false
ShowWordCount = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = true
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false
mainSections = "posts"

  [params.assets]
  disableHLJS = true
  disableFingerprinting = true
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/safari-pinned-tab.svg"

  [params.label]
  text = "Jan Kremer"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Jan Kremer"
  subtitle = "Willkommen auf meiner Webseite"
  imageUrl = "pharmacist-0.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "pharmacist-0"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Über mich"
    url = "about"

  [params.homeInfoParams]
  Title = "Willkommen auf Jan Kremers Blog 🧪"
  Content = "Dies ist ein kleines Projekt, dass ich in meiner Freizeit aufgesetzt habe. Mal schauen, wohin es führt."

  [[params.socialIcons]]
  name = "CV"
  url = "cv"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:mail@jankremer.eu"

  [[params.socialIcons]]
  name = "PGP"
  url = "about/#pgp"

  [[params.socialIcons]]
  name = "Matrix"
  url = "https://matrix.to/#/@jankremer:matrix.org"

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/janurskremer"

  [[params.socialIcons]]
  name = "Monero"
  url = "https://xmr.jankremer.eu"

  [[params.socialIcons]]
  name = "RSS"
  url = "https://jankremer.eu/index.xml"

  [params.cover]
  linkFullImages = true
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/janurskremer/jankremer.eu/blob/master/content/"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = false
disable = true
respectDoNotTrack = false
useSessionStorage = false

[privacy.instagram]
disable = true
simple = false

[privacy.twitter]
disable = false
enableDNT = false
simple = true

[privacy.vimeo]
disable = true
enableDNT = false
simple = false

[privacy.youtube]
disable = true
privacyEnhanced = false

[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 1

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = "solarized-dark"
